configfile: "config/config.yaml"
report: "report/workflow.rst"

include: "rules/common.smk"
include: "rules/pipeline.smk"

rule all:
    input:
    # Final outputs
        parse_dynamic_output('append_sfx'),
        get_report_output(),
        get_final_output()
