# Project info
User: WangRuiyu
Project: Example
Samples: config/samples_table_example.csv
Units: config/units_table_example.csv
src_fq_dir: /home/luolab/GITHUB_REPO/ScRNAseq_smkpipe_at_Luolab/workflow/data/WangRuiyu/Example/raw_fastqs
tmp_fq_dir: /mnt/WKD0P26R/TMP
aln_dir: /mnt/ZA1BT1ER/INTERMEDIATE_RES/WangRuiyu/Example/alignments
log_dir:
misc_dir: 
out_dir:

r1_extensions: ['R1.fq.gz']
r2_extensions: ['R2.fq.gz']

RNA_velocity: True

genome_fa: 
  - "/mnt/ZA1BT1ER/RESOURCES/ensembl/release_102/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna_rm.primary_assembly.fa"
gtf_annotation: /mnt/ZA1BT1ER/RESOURCES/ensembl/release_102/gtf/mus_musculus/Mus_musculus.GRCm38.102.chr.gtf
genome_index: /mnt/ZA1BT1ER/INDICES/STAR/STAR_279a_GRCm38_102_dna_rm
sjdbOverhang: "149"

ground_truth: config/barcode_ground_truth_checklist_example.csv

threads: 32
